Repository Papr1ka/KDHS-messenger, pull requests merged in 2022-08, with the labels that each got.

#2 start enviroment setup
  README.md
  libs/screen_manager/screen_manager.kv
  libs/screen_manager/screen_manager.py
  libs/screens/login_screen.kv
  libs/screens/login_screen.py
  main.py
  poetry.lock
  pyproject.toml
  settings.py
Labels: good first issue

#3 test
  settings.py
Labels: documentation

#4 test
  settings.py
Labels: documentation

#6 main screen draft
  libs/components/chat_bubble.kv
  libs/components/chat_bubble.py
  libs/components/text_input_round.kv
  libs/components/text_input_round.py
  libs/data.py
  libs/screen_manager/screen_manager.kv
  libs/screen_manager/screen_manager.py
  libs/screens/login_screen.py
  libs/screens/main_screen.kv
  libs/screens/main_screen.py
  libs/user.py
  main.py
  settings.py
Labels: enhancement

#8 created settings screen
  libs/colors.py
  libs/components/chat_bubble.kv
  libs/components/listitem.kv
  libs/components/settings_item.kv
  libs/components/settings_item.py
  libs/components/snackbar.kv
  libs/components/snackbar.py
  libs/components/text_input_round.py
  libs/components/textfield_popup.kv
  libs/components/textfield_popup.py
  libs/data.py
  libs/screen_manager/screen_manager.kv
  libs/screen_manager/screen_manager.py
  libs/screens/main_screen.kv
  libs/screens/main_screen.py
  libs/screens/settings_profile_screen.kv
  libs/screens/settings_profile_screen.py
  libs/screens/settings_screen.kv
  libs/screens/settings_screen.py
  libs/server.py
  libs/utils/behaviors.py
  libs/utils/checks.py
  main.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#9 created settings chat screen
  libs/chat.py
  libs/components/chat_bubble.kv
  libs/components/settings_item.kv
  libs/components/settings_item.py
  libs/components/snackbar.py
  libs/data.py
  libs/message.py
  libs/screen_manager/screen_manager.kv
  libs/screen_manager/screen_manager.py
  libs/screens/main_screen.kv
  libs/screens/main_screen.py
  libs/screens/settings_chat_screen.kv
  libs/screens/settings_chat_screen.py
  libs/screens/settings_profile_screen.kv
  libs/screens/settings_profile_screen.py
  libs/screens/settings_screen.kv
  libs/screens/settings_screen.py
  libs/settings.py
  libs/user.py
  main.py
Labels: enhancement
